# Workflow to check for coverage of code
name: coverage

# Controls when the workflow will run
on:
  # Workflow should run on test_suite pushes
  push:
    branches: [ sandbox ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test_package:
    name: Test Python implementation of complex numbers
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install Python dependencies
        run: pip install pytest pytest-cov numpy
      - name: Test coverage of 90%
        run: pytest --cov=src/autodiff --cov-fail-under=2
      
    
      
       


        
