# This is a basic workflow to help you get started with Actions

name: coverage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test_suite ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_complex:
    name: Test Python implementation of complex numbers
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' # let's use a recent version
      - name: Install Python dependencies
        run: pip install pytest pytest-cov
      - name: Run complex number test suite
        run: pytest --cov-report=html:tests/htmlcov --cov=tests/
      
       


        
