# Workflow to check for coverage of code
name: coverage

# Controls when the workflow will run
on:
  # Workflow should run on test_suite pushes
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test_package:
    name: Test Python implementation of complex numbers
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install Python dependencies
        run: pip install pytest pytest-cov numpy
      - name: Change into test folder and run test_harness
        run: (cd tests && ./run_tests.sh 'coverage')
      - name: Clean .gitignore in coverage output
        run: rm -f cov_html/.gitignore

      # Deploy to gh-pages branch
      - name: Deploy test coverage GitHub page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tests/cov_html
        
    
      
       


        
