name: test

# Controls when the workflow will run
on:
  # Workflow should run on test_suite pushes
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test_package:
    name: Test Automatic Differentiation package
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' 
      - name: Install Python dependencies
        run: pip install pytest pytest-cov numpy
      - name: Deploy test suite
        run: (cd tests && ls -al )
      - name: Show files
        run: ls -al
      - name: Run Tests
        run: ./run_tests.sh 'coverage'
      
    
      
       
